ALTER TABLE tb_estoque
ADD COLUMN IF NOT EXISTS produto_nome VARCHAR(255) NOT NULL DEFAULT '(Produto removido)',
ADD COLUMN IF NOT EXISTS produto_codigo VARCHAR(255) NOT NULL DEFAULT '—',
ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT TRUE;
