spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-proposta:5432/proposta_db}
    username: ${SPRING_DATASOURCE_USERNAME:proposta_user}
    password: ${SPRING_DATASOURCE_PASSWORD:proposta_pass}

  flyway:
    url: ${SPRING_FLYWAY_URL:${spring.datasource.url}}
    user: ${SPRING_FLYWAY_USER:${spring.datasource.username}}
    password: ${SPRING_FLYWAY_PASSWORD:${spring.datasource.password}}


